# Generated by Django 6.1 on 2026-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='final_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='score_breakdown',
            field=models.JSONField(default=list),
        ),
    ]
