# Generated by Django 6.1 on 2026-09-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0003_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='final_score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
