# Generated by Django 6.1 on 2026-09-28 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0005_jobdescription_recruiter_resume_recruiter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobDescription',
            new_name='Job',
        ),
    ]
