# Generated by Django 6.1 on 2026-09-29 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0007_job_department_job_education_job_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=30)),
                ('resume_file', models.FileField(upload_to='applications/resumes/')),
                ('consent_given', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('applied', 'Applied'), ('recruiter_upload', 'Recruiter Upload')], db_index=True, default='applied', max_length=20)),
                ('final_score', models.FloatField(db_index=True, default=0)),
                ('skill_score', models.FloatField(default=0)),
                ('similarity_score', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('severity_analysis', models.JSONField(blank=True, default=list)),
                ('tracking_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='resume_analyzer.job')),
            ],
        ),
    ]
