# Generated by Django 6.1 on 2026-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0010_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10),
        ),
    ]
